export default {
"login": "P-create02",
"id": 74451896,
"node_id": "MDQ6VXNlcjc0NDUxODk2",
"avatar_url": "https://avatars.githubusercontent.com/u/74451896?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/P-create02",
"html_url": "https://github.com/P-create02",
"followers_url": "https://api.github.com/users/P-create02/followers",
"following_url": "https://api.github.com/users/P-create02/following{/other_user}",
"gists_url": "https://api.github.com/users/P-create02/gists{/gist_id}",
"starred_url": "https://api.github.com/users/P-create02/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/P-create02/subscriptions",
"organizations_url": "https://api.github.com/users/P-create02/orgs",
"repos_url": "https://api.github.com/users/P-create02/repos",
"events_url": "https://api.github.com/users/P-create02/events{/privacy}",
"received_events_url": "https://api.github.com/users/P-create02/received_events",
"type": "User",
"site_admin": false,
"name": "Wojciech Sikora",
"company": null,
"blog": "",
"location": null,
"email": null,
"hireable": null,
"bio": null,
"twitter_username": null,
"public_repos": 9,
"public_gists": 0,
"followers": 0,
"following": 4,
"created_at": "2020-11-14T10:13:20Z",
"updated_at": "2021-04-16T18:39:48Z"
}